export const equipos = {
  year: 2024,
  host_country: "Estados Unidos",
  teams: [
    {
      name: "Argentina",
      group: "A",
      games_played: 0,
      games_wined: 0,
      games_lossed: 0,
      games_draw: 0,
      goals: 0,
      against_goals: 0,
      goal_difference: 0,
      points: 0,
    },
    {
      name: "Canadá",
      group: "A",
      games_played: 0,
      games_wined: 0,
      games_lossed: 0,
      games_draw: 0,
      goals: 0,
      against_goals: 0,
      goal_difference: 0,
      points: 0,
    },
    {
      name: "Chile",
      group: "A",
      games_played: 0,
      games_wined: 0,
      games_lossed: 0,
      games_draw: 0,
      goals: 0,
      against_goals: 0,
      goal_difference: 0,
      points: 0,
    },
    {
      name: "Perú",
      group: "A",
      games_played: 0,
      games_wined: 0,
      games_lossed: 0,
      games_draw: 0,
      goals: 0,
      against_goals: 0,
      goal_difference: 0,
      points: 0,
    },
    {
      name: "Ecuador",
      group: "B",
      games_played: 0,
      games_wined: 0,
      games_lossed: 0,
      games_draw: 0,
      goals: 0,
      against_goals: 0,
      goal_difference: 0,
      points: 0,
    },
    {
      name: "Jamaica",
      group: "B",
      games_played: 0,
      games_wined: 0,
      games_lossed: 0,
      games_draw: 0,
      goals: 0,
      against_goals: 0,
      goal_difference: 0,
      points: 0,
    },
    {
      name: "Mexico",
      group: "B",
      games_played: 0,
      games_wined: 0,
      games_lossed: 0,
      games_draw: 0,
      goals: 0,
      against_goals: 0,
      goal_difference: 0,
      points: 0,
    },
    {
      name: "Venezuela",
      group: "B",
      games_played: 0,
      games_wined: 0,
      games_lossed: 0,
      games_draw: 0,
      goals: 0,
      against_goals: 0,
      goal_difference: 0,
      points: 0,
    },
    {
      name: "Bolivia",
      group: "C",
      games_played: 0,
      games_wined: 0,
      games_lossed: 0,
      games_draw: 0,
      goals: 0,
      against_goals: 0,
      goal_difference: 0,
      points: 0,
    },
    {
      name: "Panamá",
      group: "C",
      games_played: 0,
      games_wined: 0,
      games_lossed: 0,
      games_draw: 0,
      goals: 0,
      against_goals: 0,
      goal_difference: 0,
      points: 0,
    },
    {
      name: "Uruguay",
      group: "C",
      games_played: 0,
      games_wined: 0,
      games_lossed: 0,
      games_draw: 0,
      goals: 0,
      against_goals: 0,
      goal_difference: 0,
      points: 0,
    },
    {
      name: "Estados Unidos",
      group: "C",
      games_played: 0,
      games_wined: 0,
      games_lossed: 0,
      games_draw: 0,
      goals: 0,
      against_goals: 0,
      goal_difference: 0,
      points: 0,
    },
    {
      name: "Brasil",
      group: "D",
      games_played: 0,
      games_wined: 0,
      games_lossed: 0,
      games_draw: 0,
      goals: 0,
      against_goals: 0,
      goal_difference: 0,
      points: 0,
    },
    {
      name: "Colombia",
      group: "D",
      games_played: 0,
      games_wined: 0,
      games_lossed: 0,
      games_draw: 0,
      goals: 0,
      against_goals: 0,
      goal_difference: 0,
      points: 0,
    },
    {
      name: "Costa Rica",
      group: "D",
      games_played: 0,
      games_wined: 0,
      games_lossed: 0,
      games_draw: 0,
      goals: 0,
      against_goals: 0,
      goal_difference: 0,
      points: 0,
    },
    {
      name: "Paraguay",
      group: "D",
      games_played: 0,
      games_wined: 0,
      games_lossed: 0,
      games_draw: 0,
      goals: 0,
      against_goals: 0,
      goal_difference: 0,
      points: 0,
    },
  ],
};
